### ISSUE TITLE
FLAG_INSTEAD_OF_REMOVE is not working

### ISSUE THREAD

**Issue by MoutatsuLai** [TomONeill/youtube-comment-filter-script#1]
I added FLAG_INSTEAD_OF_REMOVE in the code and change false but not working.
I didn't found any function named FLAG_INSTEAD_OF_REMOVE in the script.

**Comment by TomONeill** [comment]
Hmm. Seems like I did not properly commit the latest readme.
The name of that setting has changed to `FLAIR_INSTEAD_OF_REMOVE`.

Please use that setting instead (it should be somewhere at the top already)

**Comment by MoutatsuLai** [comment]
Thanks.
